### ISSUE TITLE
Laravel v5.7 compatability?

### ISSUE THREAD

**Issue by nateritter** [matt-allan/laravel-code-style#1]
Is there an easy/fast way to make this compatible with Laravel 5.7?  I'd love to use it but haven't upgraded to 5.8 quite yet.

**Comment by matt-allan** [comment]
Yeah, the code should work just fine.

Currently [we run tests on 7.1 with the --prefer-lowest flag](https://github.com/matt-allan/laravel-code-style/blob/01d29be3ed8c6d107919ba6089fe392ca162eab7/.travis.yml#L21).  If we loosen the constraints this will install 5.7 instead of 5.8.  The problem is, [we run a test to verify the formatting matches Laravel's](https://github.com/matt-allan/laravel-code-style/blob/01d29be3ed8c6d107919ba6089fe392ca162eab7/tests/FormattingTest.php#L14) and on 5.7 the formatting didn't match the latest rule set, which means that test will fail.

If we loosen the constraint in composer.json and skip that test if 5.7 is installed (with PHPUnit's `$this->markTestSkipped()`) it should work without breaking the build.

**Comment by nateritter** [comment]
Hmm.. Ok. So, I guess I'm not clear on how I could get it installed using `composer require` as I get the following no matter what I try. I'm sure I'm missing something obvious here.

```
Using version ^0.2.0 for matt-allan/laravel-code-style
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for matt-allan/laravel-code-style ^0.2.0 -> satisfiable by matt-allan/laravel-code-style[0.2.0].
    - Conclusion: remove laravel/framework v5.7.27
    - Conclusion: don't install laravel/framework v5.7.27
    - matt-allan/laravel-code-style 0.2.0 requires illuminate/support 5.8.x -> satisfiable by laravel/framework[5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.27].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.11|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.12|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.14|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.15|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.8|don't install laravel/framework v5.7.27
    - don't install illuminate/support v5.8.9|don't install laravel/framework v5.7.27
    - Installation request for laravel/framework 5.7.27 -> satisfiable by laravel/framework[v5.7.27].
```

**Comment by matt-allan** [comment]
Sorry I meant the code will work but we still need to edit the composer.json and update the tests in this repository before you can install it.

**Comment by nateritter** [comment]
Ah, ok. Thank you!

Nate Ritter
619.456.3919
https://www.linkedin.com/in/nateritter
nate@perfectspace.com

Sent via Superhuman iOS ( https://sprh.mn/?vip=nate@perfectspace.com )

**Comment by matt-allan** [comment]
`0.3.0` supports 5.7 Laravel apps.  Let me know if you run into any issues.

**Comment by nateritter** [comment]
Works like a charm, BTW. Thanks @matt-allan. Integrated into our project and now in use by all devs. Cheers!

**Comment by kevyworks** [comment]
Hi @matt-allan, would this be possible to adjust the lowest flag to Laravel 5.5.*? Thanks!

**Comment by matt-allan** [comment]
Hi @kevyworks,

That should be fine. Just need to test it and make sure it works. We can push a 0.4.x and 0.5.x tag.

**Comment by kevyworks** [comment]
@matt-allan Thanks!
