### ISSUE TITLE
Schedule TravisCI builds

### ISSUE THREAD

**Issue by lhsazevedo** [matt-allan/laravel-code-style#12]
Tests can break at any time if Laravel style rules change. For example, build is failing right now as Laravel switched to [Alpha ordered imports](https://github.com/laravel/framework/pull/29933)

By using [TravisCI cron jobs](https://docs.travis-ci.com/user/cron-jobs/) its possible to catch these with scheduled daily builds.

**Comment by matt-allan** [comment]
Great idea! I just set up a daily cron job for master.
