### ISSUE TITLE
Backport list_syntax rule to v0.4

### ISSUE THREAD

**Issue by lhsazevedo** [matt-allan/laravel-code-style#17]
The list_syntax rule was added in version 0.5 only.

Simple solution: Just release commit a4fb38b93014232165d1bd6c0603d94d65eafb77 as v0.4.1.

Best solution: Ideally, we would create a 0.4.x branch at ac5dcc39c41f7a12665dda8aafb7a40e2bc2e7a0 so that we can backport future bug fixes and features to it, as version 5.5 (LTS) will continue to receive security fixes until August 2020.

**Comment by matt-allan** [comment]
Hey @lhsazevedo,

It looks like Laravel [isn't using the short list syntax rule for 5.5](https://github.com/laravel/framework/blob/5.5/.styleci.yml). They seem to have added it in 5.6. I probably should have tagged 0.5.0 with the list_syntax rule change and 0.6.0 with the import change so you could use 0.5.0 if you were on 5.6 - 5.8 but I can't really fix it now 🙁 

I'm planning on doing a new major release of this package every time the code style changes so running `composer update` doesn't cause huge diffs next time you run `php-cs-fixer`. If we do that we can't really backport style changes as the next major version # has already been taken.

It's possible we will need to backport bug fixes but this package is only a few lines of code so it seems unlikely. It's pretty straightforward to override the preset so if someone had to upgrade to fix a bug they could override the rules that have changed like Laravel is doing with their styleci config.

It's not as future proof as creating branches for each release in advance but it should be easier to maintain.
