### ISSUE TITLE
Any plan to use Github Actions

### ISSUE THREAD

**Issue by zaherg** [matt-allan/laravel-code-style#20]
Hey, I was wondering if you have any plans to migrate to github actions.

If this is something you would like, I am more than happy to help with it.

Thanks.

**Comment by owenvoke** [comment]
I was thinking this earlier when updating the Travis configuration.

**Comment by zaherg** [comment]
The only disadvantage is that they have a limit which will be consumed out of your own account.

but if this is not a problem, I'll create a PR for you to try it

**Comment by matt-allan** [comment]
Sure! PRs welcome 😁
