### ISSUE TITLE
Convert StyleCI to PHP-CS-Fixer

### ISSUE THREAD

**Issue by szepeviktor** [matt-allan/laravel-code-style#30]
Hello! 👋 

Have you seen my converter class?
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/laravel/.php_cs

:)

**Comment by mfn** [comment]
Very nice!

Is there a proper project / readme to it? Any drawbacks?

Might me worth mention in the README…

**Comment by szepeviktor** [comment]
These are all the docs.

```
/**
 * Convert Laravel presets from StyleCI to PHP CS Fixer.
 *
 * 1. Install PHP CS Fixer: phive install php-cs-fixer
 * 2. Start: tools/php-cs-fixer fix -v --dry-run
 *
 * @see https://docs.styleci.io/presets#laravel
 * @version 1.2.0
 */
```

It is used in almost every Laravel project I take care of.

We need some effort to help those who are not content with the above docblock.

> Any drawbacks?

StyleCI changes happen completely **UNDOCUMENTED**!!!

**Comment by szepeviktor** [comment]
Do you have suggestions for custom StyleCI rules not understood by PHP CS Fixer?
Lines ending in `=> null, // FIXME`

**Comment by matt-allan** [comment]
Hi @szepeviktor, thanks for sharing. I ended up writing a similar script to automate the rule generation. You can see the mapping we're using [here](https://github.com/matt-allan/laravel-code-style/blob/6be5cc483850f3ebb961a98b825b15e223813e13/src/Dev/GenerateRules.php#L33). I'm going to close this issue but feel free to reach out if you want to discuss anything further.
