### ISSUE TITLE
maybe lost "remove empty line between use"

### ISSUE THREAD

**Issue by guoxiangke** [matt-allan/laravel-code-style#4]
Thanks for this package, but maybe lost one rule,
this is from https://github.styleci.io/analyses/8PbeKW
![image](https://user-images.githubusercontent.com/1160703/60169552-7e3d1180-9839-11e9-8bfb-ae252cf6ebc5.png)

**Comment by matt-allan** [comment]
Hello,

Thanks for the report. This should now be fixed in the master branch.
