### ISSUE TITLE
Add 'array_indentation' => true

### ISSUE THREAD

**Issue by bilogic** [matt-allan/laravel-code-style#44]
Hi,

Possible to add this `'array_indentation' => true` configuration as default?
It is to fix Laravel config files like below. Thank you.

```PHP
<?php

return [
    /*
     * Some comments
     */
'api_key' => env('API_KEY'), // indents this line properly
    ...
```

**Comment by matt-allan** [comment]
Hi,

This is already enabled: 

https://github.com/matt-allan/laravel-code-style/blob/397417c7bb2eca46000d6e3625c601e7b1cfceae/src/Config.php#L21

**Comment by bilogic** [comment]
Hi,

Thanks for getting back!

I checked, https://github.com/matt-allan/laravel-code-style/archive/refs/tags/0.6.0.zip doesn't have it.
Not sure where the release went wrong. I'm loading `0.6.0` using composer.

**Comment by matt-allan** [comment]
Oh it was added in #35. I missed it in the changelog. 

I will update the changelog and tag a new release as soon as I get a chance. 

In the interim you can pull the main branch via composer or add the override in your own config.

**Comment by bilogic** [comment]
Yea already did that. Thank you!
