### ISSUE TITLE
Braces on anonymous classes

### ISSUE THREAD

**Issue by jasonvarga** [matt-allan/laravel-code-style#47]
First of all, thanks for this package. I just discovered it and it will make maintaining a local phpcs much simpler. 🎉 

**Describe the bug**

On StyleCI, anonymous classes put the braces on the next line.

I'm using `dev-main` of this package (at a80e10e) and it puts them on the same line.

You can see this here: https://github.com/statamic/cms/pull/3639/files

This has only started happening recently. You [merged code yesterday](https://github.com/matt-allan/laravel-code-style/pull/46) that concerns "braces" so I had assumed it was attempting to fix the recent change on StyleCI.

**To Reproduce**
1. Write an anonymous class with a brace on the next line.
    ```php
    return new class
    {
       //
    }
    ```
2. Run the fixer, and see it put the brace on the same line.
    ```php
    return new class {
       //
    }
    ```
3. Push code so StyleCI runs the `laravel` preset. See that it moved the brace back to the following line (as per step 1).
    ```php
    return new class
    {
       //
    }
    ```

**Expected behavior**
PHP-CS Fixer should be consistent with StyleCI.

**Desktop:**
 - OS: MacOS 11.2.3

**Comment by matt-allan** [comment]
Hey,

Thanks for reporting this. This makes it sound like StyleCI is setting [`position_after_anonymous_constructs` to `next`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/basic/braces.rst#position_after_anonymous_constructs) instead of the default of `same`. All the rule says is:

> Structural bodies MUST be enclosed by braces and properly indented. Braces MUST be properly placed, allowing empty anonymous classes.

...which makes it a bit difficult to guess what the config should be. There may be other settings for the `braces` rule that are incorrect too.

**Comment by jasonvarga** [comment]
Changing that to `next` looks like it'll change closures too, which definitely isn't something in Laravel's style guide.

![image](https://user-images.githubusercontent.com/105211/117034393-43c41b80-acd1-11eb-878b-5d0475bda27c.png)

(Unless I've configured it wrong)

```php
    ->setRules([
        '@Laravel' => true,
        '@Laravel:risky' => true,
        'braces' => [
            'position_after_anonymous_constructs' => 'next'
        ]
    ])
```

**Comment by matt-allan** [comment]
It doesn't look like it's possible to keep the brace on the same line for closures but not for classes with the braces fixer. I tried with PHP-CS-Fixer 3.0 and got the same result, and from reading the code it looks like it treats both anonymous classes and closures the same.

The change I merged yesterday only applies to anonymous classes without a body so I don't think it's related to this.

It looks like [the braces fixer is going to be split into separate fixers](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4885), at which point we will be able to set `anonymous_functions_opening_brace => same_line` and `anonymous_classes_opening_brace => next_line_unless_newline_at_signature_end` which should fix this. Until then I think our only option would be to fork the braces rule.

It's likely that StyleCI is using a forked version that includes the unreleased fixers from that PR, based on the behavior and [this issue](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4984#issuecomment-636516591).

**Comment by jasonvarga** [comment]
So we just have to deal with PHP-CS Fixer doing one thing and StyleCI doing another until that PR is merged? Bummer. Thanks for the info!

**Comment by matt-allan** [comment]
With the latest tag the `braces` and `class_definition` rules are not enabled automatically which prevents PHP-CS-Fixer from changing the formatting from what Style CI does, but it will allow some invalid formatting through until we can use the separate braces fixers.
