### ISSUE TITLE
Seeking new maintainers

### ISSUE THREAD

**Issue by matt-allan** [matt-allan/laravel-code-style#61]
I don't want to maintain this package anymore. If you're interested in maintaining it fork the repo, let me know, and I will archive this one and recommend your fork as an alternative.

**Comment by Jubeki** [comment]
Hey @matt-allan,

I am willing to maintain this package: https://github.com/Jubeki/laravel-code-style

What have I done already:
- Added Support for PHP 8.1
- Added Support for Laravel 9
- Created 0.8.0 Tag and GH Release
- Checked if packagist is working correctly

If it is okay with you I would like to keep the namespace `MattAllan\LaravelCodeStyle` in the Source Code.
Also I didn't remove you from the authors and would only do that if you don't want to be named anymore.

If you still want to maintain this package, then I will send a PR accordingly for the upgrade.

Thank you for all your work so far. :heart:

EDIT:
- Added `laravel_phpdoc_alignment` Fixer
- Added `laravel_phpdoc_order` Fixer
- Added `laravel_phpdoc_separation` Fixer
- Tagged 0.8.1 with these changes

**Comment by matt-allan** [comment]
Hey @Jubeki, thanks for doing all of that! That sounds good, I will drop a link here to your fork. I think it may be confusing to keep the namespace long term but I get wanting to keep it for now to minimize churn for anyone that's upgrading. If you could change the namespace next time you tag a breaking version that would be cool just so I don't get questions about it 😁

**Comment by Jubeki** [comment]
Sure, that is no problem. It is mostly a search, replace and giving an upgrade guide. 👍

**Comment by owenvoke** [comment]
Thank you @Jubeki for taking on this package! That's great that it will continue to be maintained. 🥳

**Comment by matt-allan** [comment]
Thanks @Jubeki and everyone else that's contributed over the years, I really appreciate it ❤️

I've pointed everything to the fork and I'm going to archive this now.
