### ISSUE TITLE
Doesn't indent or remove blank lines

### ISSUE THREAD

**Issue by ghost** [matt-allan/laravel-code-style#62]
Running dev-main as constraint I noticed that when saving my file code did not get indented ad before, it also left some whitespace which normally got removed.

I tried running php-cs-fixer manually on the file, without a config so it used `default` and that did fix the indentation and whitespace.

Am I doing something wrong?

**Before:**
```php
    public function bla(Request $request)
    {
            $foo = 'bar';

        }

return view('foo');
    }
```

**After manually calling php-cs-fixer:**
```php
    public function bla(Request $request)
    {
           $foo = 'bar';
        }

            return view('foo');
    }
```

`.php-cs-fixer.php` in my root folder:
```php
<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/bootstrap/app.php';

return (new MattAllan\LaravelCodeStyle\Config())
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(app_path())
            ->in(config_path())
            ->in(database_path())
            ->notPath(database_path('migrations'))
            ->in(resource_path('lang'))
            ->in(base_path('routes'))
            ->in(base_path('tests'))
            ->in(base_path('Blacklight'))
            ->in(base_path('misc'))
    )
    ->setRules([
        '@Laravel' => true,
        'no_unused_imports' => true,
    ]);

```

**Comment by matt-allan** [comment]
I don't understand the code sample. Isn't that invalid PHP code?

When you run with the default config it will tell you what rules applied to the fixed code. Then you can check if those rules are enabled for the Laravel preset. From there try enabling the rules and see if that fixes it.

It's hard for me to help beyond that without further information. My guess is adding the `braces` rule will fix it; we had to disable it because the version shipped with PHP-CS-Fixer is not compatible with StyleCI's version and causes invalid formatting of the Laravel code base in our test suite. If that fixes your issue feel free to enable it in your config, but we can't enable it in this repo by default until someone patches it and fixes the Laravel incompatibilities (see #47).

**Comment by ghost** [comment]
> I don't understand the code sample. Isn't that invalid PHP code?

You're right, must have happened when copy and pasting. Anyway, even on proper code it does the same thing, even with `'braces' => true,` in my `.php-cs-fixer.php`.

What's odd is that if I run "Format Document" from the command pallette then I see a quick `php-cs-fixer: finished` note in the statusbar at the bottom of VSCode. It also properly indents the `return` in my code.

When I run the command `php-cs-fixer fix` from the command pallete (CMD SHIFT P) then I get output in my OUTPUT tab of VSCodes console window and the code is not indented.

When I save the file the same thing happens, a lot of stuff isn't indented properly or it's not running php-cs-fixer at all. I have enabled onsave in my config:

```json
{
    "php.suggest.basic": false,
    "php.validate.enable": false,
    "[php]": {
        "editor.defaultFormatter": "junstyle.php-cs-fixer"
    },
    "php-cs-fixer.lastDownload": 1635343519987,
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.executablePath": "/Users/MY_USERNAME/.composer/vendor/bin/php-cs-fixer",
    "php-cs-fixer.pathMode": "override"
}
```

And then my local PHP and php-cs-fixer version of my Mac:

```bash
~ ➜ php -v
PHP 8.0.12 (cli) (built: Oct 21 2021 06:07:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
~ ➜ /Users/MY_USERNAME/.composer/vendor/bin/php-cs-fixer --version
PHP CS Fixer 3.3.2 Trinacria by Fabien Potencier and Dariusz Ruminski
~ ➜
```

**Comment by ghost** [comment]
Hmm. I just added `"php-cs-fixer.documentFormattingProvider": true,` which seems (after a restart) now do formatting on save.

Not sure why choosing php-cs-fixer fix from the command pallette doesnt work but this will do the trick for now.
